### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by SHAOTAO1998** [Chaos-v/DOA-Estimation#1]
Where is the location of the file and why is it not found

**Comment by Chaos-v** [comment]
You can run datarawGenerator.py to generate a set of test data(mat format) firstly, observe the path of the test data, and then run the algorithm itself.

**Comment by Chaos-v** [comment]
The 'file path' you mentioned may be ".\\dataraw".
I suggest that you create a 'dataraw' folder firstly (because I did not write the code to create the folder), then run "datarawGenerator.py" to generate a set of test data. Observe the path of this test data, change it to this path where the algorithm itself calls the path, and finally run the algorithm itself.
